[package]
name = "fc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aurora_fsm = {path = "../aurora_fsm"}
event_gen = {path = "../event_gen"}
