#!/bin/bash

git commit --no-verify -q -m "Save index" # Do a temporary commit of the staged changes
STASH=$(git stash create | xargs echo -n) # Push all unstaged changes to the stash
git reset -q --hard HEAD # Clean the working directory
git reset -q --soft HEAD^ # Undo the temporary commit, restoring the staged changes into the staging area

function hook_cleanup {
  if [ -n "$STASH" ]
  then
    git stash apply -q $STASH # Reapply unstaged changes
  fi
  exit $1
}

echo "[PRE-COMMIT HOOK] Checking formatting..."
cargo fmt --check
RET_CODE=$?

if [ $RET_CODE != 0 ]; then
  echo "[PRE-COMMIT HOOK] Format check failed. Please run cargo fmt before committing. Remember to git add changes caused by cargo fmt."
  hook_cleanup $RET_CODE
fi

hook_cleanup 0