[package]
name = "aurora_controls"
version = "0.1.0"
authors = ["Klark007 <jan.grunder@yahoo.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
