[package]
name = "event_gen"
version = "0.1.0"
authors = ["Klark007 <jan.grunder@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
