[package]
name = "nicollier_trajectory_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
serde = { version = "1.0.190", features = ["derive"] }
csv = "1.3"
anyhow = "1.0"