[Process]
    [Process.Sensor1]
    pressure = "u32"
    temp = "u16"

    [Process.Sensor2]
    y_acc = "u64"
    z_acc = "u64"

    [Process.Sensor2.x_acc]
    type = "u64"
    size = 10


[Control]
state = "String"
    [Control.Actuator1]
    x = "f32"
    y = "i32"

    [Control.Actuator2]
    x = "i32"
    y = "i32"
