[Process]
    [Process.Sensor1]
    pressure = "u32"
    temp = "u16"

    [Process.Sensor2]
    x_acc = "u64"
    y_acc = "u64"
    z_acc = "u64"

[Control]
    [Control.Actuator1]
    x = "i32"
    y = "i32"

    [Control.Actuator2]
    x = "i32"
    y = "i32"
