[package]
name = "aurora_hal"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
event_gen = { path = "../event_gen" }
arrayvec = "0.7"
anyhow = "1.0"